FEAT: MultiGPU for golang bindings
ingonyama-zk/icicle pull request #417
Opened 2024-03-04 15:08 UTC by jeremyfelder

## Describe the changes

This PR adds multi gpu support in the golang bindings.

Tha main changes are to DeviceSlice which now includes a `deviceId` attribute specifying which device the underlying data resides on and checks for correct deviceId and current device when using DeviceSlices in any operation.

In Go, most concurrency can be done via Goroutines (described as lightweight threads - in reality, more of a threadpool manager), however, there is no guarantee that a goroutine stays on a specific host thread. Therefore, a function `RunOnDevice` was added to the cuda_runtime package which locks a goroutine into a specific host thread, sets a current GPU device, runs a provided function, and unlocks the goroutine from the host thread after the provided function finishes. While the goroutine is locked to the hsot thread, the Go runtime will not assign other goroutines to that host thread

2024-03-05 13:13 UTC, DmytroTym commented
@jeremyfelder one thing I found really useful when designing Rust-side device slices is the ability to look up device id of any device pointer using CUDA runtime [cudaPointerGetAttributes](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__UNIFIED.html#group__CUDART__UNIFIED_1gd89830e17d399c064a2f3c3fa8bb4390) function. This allows to avoid explicitly storing device id alongside the actual data.

2024-03-06 11:55 UTC, ImmanuelSegol requested changes

2024-03-06 11:55 UTC, ImmanuelSegol commented on wrappers/golang/core/slice.go
> +func (d DeviceSlice) CheckDevice() {
document this with a comment please

2024-03-06 11:55 UTC, ImmanuelSegol commented on wrappers/golang/cuda_runtime/device_context.go
> +	if err != CudaSuccess {
is `err` a descriptive error?

if so perhaps its worth adding it to the panic.

2024-03-12 16:25 UTC, ImmanuelSegol approved these changes
its the same design as the rust version of multigpu so no comments on design.

The code looks good. no blocking comments so i just added some suggestions.

2024-03-12 16:25 UTC, ImmanuelSegol commented on wrappers/golang/internal/generator/templates/curve.go.tmpl
>  {{end}}
missing extra line

2024-03-12 16:25 UTC, ImmanuelSegol commented on wrappers/golang/internal/generator/templates/scalar_field.go.tmpl
>  }{{- end}}
extra line

2024-03-13 07:57 UTC, LeonHibnik approved these changes

2024-03-13 14:19 UTC, merged