verify and assert correct t-parameter for Poseidon hasher
ingonyama-zk/icicle pull request #652
Opened 2024-11-10 14:12 UTC by yshekel

2024-11-10 14:18 UTC, mickeyasa requested changes

2024-11-10 14:18 UTC, mickeyasa commented on icicle/src/hash/poseidon.cpp
> +    ICICLE_LOG_ERROR << "Poseidon only supports t values of 3, 5, 9, or 12.";
why do you always print that

2024-11-10 14:40 UTC, yshekel commented on icicle/src/hash/poseidon.cpp
> +    ICICLE_LOG_ERROR << "Poseidon only supports t values of 3, 5, 9, or 12.";
excellent question :)

2024-11-10 17:20 UTC, yshekel commented on icicle/src/hash/poseidon.cpp
> +    ICICLE_LOG_ERROR << "Poseidon only supports t values of 3, 5, 9, or 12.";
fixed

2024-11-10 17:26 UTC, mickeyasa approved these changes

2024-11-11 07:28 UTC, danny-shterman approved these changes

2024-11-11 08:59 UTC, merged