Update hash.md
ingonyama-zk/icicle pull request #710
Opened 2024-12-29 14:39 UTC by ShaniBabayoff

Copying the Supported Bindings section from poseidon2.md.

## Describe the changes

This PR...

## Linked Issues

Resolves #

2024-12-30 07:05 UTC, jeremyfelder commented on docs/docs/icicle/primitives/hash.md
> +[`Rust`](https://github.com/ingonyama-zk/icicle/tree/main/wrappers/rust/icicle-core/src/poseidon2)
Go also supports Poseidon2, although it is per curve/field, for example for [bn254](https://github.com/ingonyama-zk/icicle/blob/main/wrappers/golang/curves/bn254/poseidon2/poseidon2.go)

2024-12-30 07:06 UTC, jeremyfelder commented on docs/docs/icicle/primitives/hash.md
> +## Supported Bindings
Why is this section Poseidon2 specific?
If we want to keep it poseidon2 specific, it should be a header 4 under the Poseidon2 header 3.

2025-01-01 09:37 UTC, ShaniBabayoff commented on docs/docs/icicle/primitives/hash.md
> +## Supported Bindings
DONE

2025-01-01 09:42 UTC, ShaniBabayoff commented on docs/docs/icicle/primitives/hash.md
> +[`Rust`](https://github.com/ingonyama-zk/icicle/tree/main/wrappers/rust/icicle-core/src/poseidon2)
done

2025-01-01 20:32 UTC, yshekel commented on docs/docs/icicle/primitives/hash.md
> +This is the most basic way to use the Poseidon2 API. See the [examples/poseidon2](https://github.com/ingonyama-zk/icicle/tree/b12d83e6bcb8ee598409de78015bd118458a55d0/examples/rust/poseidon2) folder
what is this commit? is it merged to main?

2025-01-01 20:35 UTC, yshekel commented on docs/docs/icicle/primitives/hash.md
> +#### Merkle Tree Builder
why merkle on the hash page?

2025-01-01 20:36 UTC, yshekel commented on docs/docs/icicle/primitives/hash.md
> +#### Rust API
I dont understand what this should be here. Maybe in the rust page as a poseidon2 example below.
 https://github.com/ingonyama-zk/icicle/blob/main/docs/docs/icicle/rust-bindings/hash.md

2025-01-01 20:36 UTC, yshekel requested changes
I think this is not the correct page to update. Merkle should be removed from hash page. Rust example can be under the rust hash page https://github.com/ingonyama-zk/icicle/blob/main/docs/docs/icicle/rust-bindings/hash.md

2025-01-09 11:08 UTC, closed without merging